### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by bootstraponline** [facebook/FBSimulatorControl#253]
https://travis-ci.org/facebook/FBSimulatorControl/builds

[![Build Status](https://travis-ci.org/facebook/FBSimulatorControl.svg?branch=master)](https://travis-ci.org/facebook/FBSimulatorControl)

even on 7.2 https://github.com/facebook/FBSimulatorControl/pull/252

**Comment by lawrencelomax** [comment]
Looks like @marekcirkos has fixed this in #252
