### ISSUE TITLE
fbsimctl fails to boot simulator via UDID

### ISSUE THREAD

**Issue by bootstraponline** [facebook/FBSimulatorControl#254]
I'm using rev c21b770d41138f2b866079f31ce41f38ab8f7bc7 with Xcode 7.3 on OS X 10.11.4.

```
$ ./build/Build/Products/Debug/fbsimctl boot 89E58B5D-AAC2-4A71-B10E-57A8BF6AEF76
No Query Provided
```

**Comment by lawrencelomax** [comment]
`fbsimctl` varies from `simctl` in that the UDID comes first, this makes it possible to chain actions. 

`fbsimctl 89E58B5D-AAC2-4A71-B10E-57A8BF6AEF76 boot` should do what you need, you can put multiple UDIDs before the action (`boot`). The [Unit tests for command parsing](https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift) will also help identify what is and what isn't parsable.

**Comment by bootstraponline** [comment]
I think this is a common enough mistake that a useful error message would be appropriate.

**Comment by meiravm** [comment]
Can I boot the same device twice? 
Booting one and then trying the other one with different port only changes the port for the first one:
fbsimctl DE2A619E-800A-4562-8FEA-8F9A0C7FB123 boot -- listen --http 8200 
fbsimctl DE2A619E-800A-4562-8FEA-8F9A0C7FB123 boot -- listen --http 8300
