### ISSUE TITLE
Help output is too useful

### ISSUE THREAD

**Issue by bootstraponline** [facebook/FBSimulatorControl#255]
```
$ ./build/Build/Products/Debug/fbsimctl help
Help
```

I know this is mentioned in https://github.com/facebook/FBSimulatorControl/issues/70 but maybe it'd be better to say:
> "Help information coming soon..."

**Comment by lawrencelomax** [comment]
The plumbing is in, that doesn't mean the help is ready yet. I'll put some unimplemented message in there.

**Comment by lawrencelomax** [comment]
Duping to #256
