### ISSUE TITLE
fbsimctl: Help output is not useful

### ISSUE THREAD

**Issue by bootstraponline** [facebook/FBSimulatorControl#256]
> $ ./build/Build/Products/Debug/fbsimctl help_pls
Failed to Parse Command '["help_pls"]' does not match '[At least 0 of Any of [--debug-logging, --json, ---pretty] followed by help, At least 0 of Any of [--debug-logging, --json, ---pretty] followed by --set followed by A Directory followed by At least 0 of Any of [--delete-all, --kill-all, --kill-spurious, --ignore-spurious-kill-fail, --kill-spurious-services, --timeout-resiliance] followed by Any of [all, At least 1 of Any of [Any of [--state=creating, --state=shutdown, --state=booting, --state=booted, --state=shutting-down], A NSUUID, A Device Name followed by An OS Version followed by --aux followed by A Directory]] followed by At least 1 of Any of [--udid, --name, --device-name, --os, --state, --pid] followed by At least 1 of Any of [approve followed by At least 1 of Any of [An Application, A Bundle ID], boot followed by --locale followed by A Locale followed by Any of [--scale=25, --scale=50, --scale=75, --scale=100] followed by At least 1 of Any of [--connect-bridge, --direct-launch, --use-nsworkspace, --debug-window], create followed by A Device Name followed by An OS Version followed by --aux followed by A Directory, delete, diagnose followed by Any of [--current-format, --path, --content] followed by Any of [Any of [An Application, A Bundle ID] followed by At least 1 of Anything, At least 1 of --name followed by Anything, --crashes-since followed by Of Double followed by At least 0 of Any of [--application, --system, --custom-agent]], install followed by An Application, launch followed by Any of [A Binary followed by Many of Anything, Any of [An Application, A Bundle ID] followed by Many of Anything], listen followed by Any of [--socket followed by Of Int, --http followed by Of Int], list, open followed by A NSURL, record followed by Any of [start, stop], relaunch followed by Any of [An Application, A Bundle ID] followed by Many of Anything, shutdown, tap followed by Of Double followed by Of Double, terminate followed by Any of [An Application, A Bundle ID], upload followed by At least 1 of A File]]'
Help

**Comment by lawrencelomax** [comment]
This is on my list of things to do to improve the UI before a homebrew release. We currently have the message for the failing parser, but then too much context is recursively added, meaning that the message becomes a bit crazy.

**Comment by lawrencelomax** [comment]
@amnn has made a massive difference here with recent commits. Closing now and if there's further refinements to make, we can take them up in separate tasks.
