### ISSUE TITLE
Booted sims can not be resized

### ISSUE THREAD

**Issue by sapieneptus** [facebook/FBSimulatorControl#271]
We have four options for launch configurations:

- FBSimulatorLaunchOptionsConnectBridge
- FBSimulatorLaunchOptionsEnableDirectLaunch
- FBSimulatorLaunchOptionsShowDebugWindow
- FBSimulatorLaunchOptionsUseNSWorkspace 

Of these,  `FBSimulatorLaunchOptionsConnectBridge`, `FBSimulatorLaunchOptionsShowDebugWindow`, and `FBSimulatorLaunchOptionsUseNSWorkspace` launch the simulator in a state such that it can not be resized. 

I don't know if `FBSimulatorLaunchOptionsEnableDirectLaunch` works, as I have never been able to get a sim to launch successfully with this option - it appears to be a no-op. 

Maybe I'm looking in the wrong place?

**Comment by marekcirkos** [comment]
When you boot with `FBSimulatorLaunchOptionsEnableDirectLaunch` it will start simulator but it will not open Simulator application. This way you operate simulator "in the background" which is lighter as system does not have to render it.

**Comment by sapieneptus** [comment]
@marekcirkos Yes, I figured that. However, when I boot in this way and then do a check of the simulator `state` on a subsequent run, it is reporting `shutdown`. 

Regardless, it sounds whatever is causing the resizing issue is present in all three other methods? Is this a known issue? I don't see any config options that seem to control the _ability_ to resize. 

Launching with different initial scales doesn't seem to help either.

**Comment by marekcirkos** [comment]
We use simulators in automated way, so there is no need for resizing by hand.
 Do you mind saying what is your use case?

**Comment by sapieneptus** [comment]
I suppose the obvious one is if someone is debugging their test (or debugging the Driver itself during an integration test).

**Comment by sapieneptus** [comment]
Or suppose someone simply wanted to launch a sim and make a tiny CLI over FBSimulatorControl to launch a sim of their choosing - they'd probably want to be able to resize it as is usual.

**Comment by lawrencelomax** [comment]
We essentially fix the size by passing the value in the arguments as an NSUserDefault. If you need to resize, don't pass a scale value. Since the NSUserDefaults is shared by all Simulator apps it's not possible to initially override with an argument but allow the user to change it at runtime without shimming.

**Comment by lawrencelomax** [comment]
I think this is a wontfix so closing. If there's any other points that you think are important, please let us know.
