### ISSUE TITLE
Can not upload app data bundle on 32 bit arch devices

### ISSUE THREAD

**Issue by sapieneptus** [facebook/FBSimulatorControl#272]
So far, iPod Touch 5th Gen (Apple A5 32 bit chip) and iPhone 5 (Apple A6 32 bit chip) fail on data bundle upload (as part of starting an xctest). iPhone 6 (64 bit) works fine. 

I'm not sure if this is resolvable, as even Xcode has trouble with the container data for those devices (both displaying and downloading), was wondering if you guys had some insight into workarounds?

**Comment by sapieneptus** [comment]
I'm still trying to rule out it being a problem just on my machine, though if it is possible to get a Xcode into this state accidentally it would be good to have steps to resolve.

**Comment by marekcirkos** [comment]
I have seen this issue once and I think you are up to something. Can you try restarting device? or even host?

**Comment by marekcirkos** [comment]
Good news I just put up a diff for better error handling, which give you more information if something has failed.

**Comment by sapieneptus** [comment]
Rebooted host and crashed xcode, then they started working again. Very odd. Maybe some problem with `usbmuxd` or something ?

**Comment by marekcirkos** [comment]
I am not sure to be honest.
