### ISSUE TITLE
iOS 10 Support

### ISSUE THREAD

**Issue by sapieneptus** [facebook/FBSimulatorControl#273]
Hi guys, 

Is iOS10 (beta 1) supposed to work already for launching `XCUITest` bundles? When I attempt to run a test via the `FBDeviceControl` methods, it seems to upload an xctestconfiguration correctly, but when my runner launches it keeps choosing an old configuration file so the session identifiers don't match. 

Specifically, I can create the configuration and device operator without issue, but when I get here:
```
[testRunStrategy startTestManagerWithAttributes:@[] environment:@{} error:&innerError];
```
It hangs on this:
```
2016-06-27 14:02:51.943 xctest[38756:727415] SessionID: <__NSConcreteUUID 0x114c243e0> <Some ID>
```
And eventually fails with
```
2016-06-27 14:03:30.125 xctest[38756:727415] Err: Error Domain=com.facebook.XCTestBootstrap Code=0 "Failed connect to test runner or test manager daemon" UserInfo={NSLocalizedDescription=Failed connect to test runner or test manager daemon}
```

In the device logs, I see the session identifier doesn't match. 

I pulled the latest master this morning.

**Comment by marekcirkos** [comment]
We are still working on Xcode 8 support. In your particular case I suspect that, application data containing test configuration, test bundle etc is not actually getting pushed to device even if it claims that it was successful. I have similar issue when starting test from clean state. It simply fails as injected frameworks are not there.

**Comment by sapieneptus** [comment]
I believe it is getting pushed, as I see the contents in the container inspector via Xcode. 

Interestingly, when the app data bundle gets pushed, the phone immediately locks (if I don't pause the execution at that step and manually unlock the phone, it actually throws a bad access error). Perhaps it's just a beta 1 issue....

**Comment by sapieneptus** [comment]
Just FYI, I pulled the latest master today and it doesn't look like it builds on Xcode 8 anymore. Needed to `#import <mach/mach_port.h>` in FBSimulatorHID.h .

**Comment by lawrencelomax** [comment]
> Just FYI, I pulled the latest master today and it doesn't look like it builds on Xcode 8 anymore

I'll take a look at this.

**Comment by lawrencelomax** [comment]
We've had iOS 10 support for a while now.
