### ISSUE TITLE
Simulator's connection is `nil` unless explicitly launched

### ISSUE THREAD

**Issue by sapieneptus** [facebook/FBSimulatorControl#276]
If you have a simulator that is already running and you want to run a test, the test will fail with a "can not connect" message (see below) because the `FBSimulator` will not initialize the `connection` unless you explicitly `boot` it within the same process:

```
NSUnderlyingError=0x7fd1621d41f0 {Error Domain=com.facebook.FBSimulatorControl Code=0 "Could not connect bridge to Simulator in order to launch application App Launch <app name>
```

The 'problematic' code is in `FBSimulatorBootStrategy.m`:

```objective-c
- (BOOL)boot:(NSError **)error
{
  // Return early depending on Simulator state.
  if (self.simulator.state == FBSimulatorStateBooted) {
    return YES;
  }
  
  //...
  //<snip>
  //...

  [self.simulator.eventSink connectionDidConnect:connection];

  return YES;
}
```

This might not be your intended use case for running tests, _but_ if someone is using `fbsimctl` as a standalone binary, launches a sim and then tries to run a test, I think they will experience this same problem.

**Comment by lawrencelomax** [comment]
Thanks for the writeup, it does make sense for us to create the connection if the Simulator has been booted by another process. Attaching to a process booted by another simulator is fine, the `SimulatorBridge` can be connected regardless. The Framebuffer and HID are a different story, but those properties are nullable anyway.
