### ISSUE TITLE
How to run UITests once WDA is launched

### ISSUE THREAD

**Issue by anshu10165** [facebook/FBSimulatorControl#284]
I was able to successfully start WDA using : **fbsimctl --state=booted \launch_xctest /Users/anray/Library/Developer/Xcode/DerivedData/WebDriverAgent-coxwrbfiscbrpzexnaqixqobjpxo/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.test.booking.debug --port 8100 --\listen**
Few queries related to running UITests using fbsimtcl:

-> Before starting the WDA, do I need to boot required simulators , I believe yes, Thoughts ?
-> Once WDA is started , how should I run my UITests using XCTool command line code now, and on multiple simulators, usecase is , I have 4-5 tests and I want each one of them to run on different booted simulators.

**Comment by lawrencelomax** [comment]
> Before starting the WDA, do I need to boot required simulators

Yes this is correct. The `--state=booted` argument you have there will target *all* booted Simulators. You can pass a Simulator UDID instead if you want to target a Single Simulator. If you pass the UDID you can ensure that WDA will be running on different ports if you have multiple Simulators.

> Once WDA is started , how should I run my UITests using XCTool command line code now, and on multiple simulators, usecase is , I have 4-5 tests and I want each one of them to run on different booted simulators.

We don't have an out-of-the box solution for doing this. There are a number of WebDriver client libraries around for a number of languages and platforms. There's also a lot of other information out there about using WebDriver generally.

You will be able to start a WebDriver Session using the HTTP Wire Protocol. There is some [documentation on a few of the commands on the WebDriverAgent Wiki](https://github.com/facebook/WebDriverAgent/wiki/Queries). If you wanted to have tests in Obj-C/Swift, you can certainly do this by making a Mac OS X test target and talking to WDA over HTTP.

Closing. If you have follow-up questions, please re-open and I'll get back to you.

**Comment by anshu10165** [comment]
@lawrencelomax : Thanks for quick response , have one more query in case you could address
fbsimctl --simulators $UDID launch_xctest **$APP/PlugIns/tests.xctest** com.test.booking.debug 

On the above command , what should be the path to tests.xctest, should it be path to WebDriverAgent.xctest or can I give my own xctest path to it?
