### ISSUE TITLE
fbsimctl: how to set Location with Latitude and Longitude?

### ISSUE THREAD

**Issue by noshuai** [facebook/FBSimulatorControl#287]
Does fbsimctl support  to set Location with Latitude and Longitude?

**Comment by lawrencelomax** [comment]
This is absolutely [possible at the API level](https://github.com/facebook/FBSimulatorControl/blob/bb33ddcf8fdab607139c12127e192b4ef624018d/FBSimulatorControl/Management/FBSimulatorBridge.h#L51), it's just not yet exposed to `fbsimctl` proper. Shouldn't be too much work to get this done however.

**Comment by noshuai** [comment]
#288

**Comment by agileseph** [comment]
It will be much better do not hardcode Latitude and Longitude during boot to custom point 

> [bridge setLocationWithLatitude:37.485023 longitude:-122.147911]; - FBSimulatorControl/Strategies/FBSimulatorBootStrategy.m

 and then expose the set Latitude and Longitude method into a standalone command of fbsimctl. In general, I think it is good idea do not customize any default behavior.

**Comment by lawrencelomax** [comment]
This was implemented a while back.
