### ISSUE TITLE
Does / will fbxctest support running xctest programmatically without any console tools?

### ISSUE THREAD

**Issue by larryonoff** [facebook/FBSimulatorControl#298]

**Comment by lawrencelomax** [comment]
If you're meaning that the core functionality will be available via a library and Objective-C API, the answer will probably be yes. This is the strategy that we've taken with FBSimulatorControl/fbsimctl and it's worked out very well for us. 

The cli becomes a thin wrapper around the Framework. The cli has some additional code specialised for cli output. You can see that some of this API is already used outside of a cli context, as FBSimulatorControl has a set of tests that will run 3rd party bundles.

**Comment by larryonoff** [comment]
Thank you. If I understand you properly, this's exactly what I need.

I need a functionality that builds the app -> uploads build on the device -> starts / runs tests in the app -> app sends results to my server.

It looks that It isn't available since you tell `will`. Am I correct?

**Comment by lawrencelomax** [comment]
There's currently a lot that you can currently do. It sounds like you want to run Application Tests, which is currently implemented. You should take a look at [`FBSimulatorControlTestInjectionTests`](https://github.com/facebook/FBSimulatorControl/blob/master/FBSimulatorControlTests/Tests/Integration/FBSimulatorTestInjectionTests.m), which runs a test bundle against a System Application and confirms that the correct test success/failure methods are called. This may be enough to do what you need.

**Comment by larryonoff** [comment]
Thanks for the answer!
