### ISSUE TITLE
Not able to use Key board in Simulators launched by fbsimctl

### ISSUE THREAD

**Issue by kapilag** [facebook/FBSimulatorControl#305]
Hi 

I am using fbsimctl for testing on different simulators and my app requires loads of data to be filled in. Using keyboard of simulator is not very efficient. Can someone please help.?

**Comment by lawrencelomax** [comment]
We don't use `fbsimctl` for automating UI interactions. There is a `tap` API, but it's not going to be a good way for you to interact with the UI. 

You should [take a look at `WebDriverAgent`](https://github.com/facebook/webdriveragent), which talks directly to the iOS XCTest APIs.

**Comment by kapilag** [comment]
Ohk thanks for the reply, actually i thought of using it for manual checking on different simulator for sanity, but i think thats not the best case for fbsimctl
