### ISSUE TITLE
Unable to install via HomeBrew

### ISSUE THREAD

**Issue by DNCGraef** [facebook/FBSimulatorControl#311]
BDSPUKA00000157:fbsimctl Dan$ brew install fbsimctl
==> Installing fbsimctl from facebook/fb
==> Installing dependencies for facebook/fb/fbsimctl: carthage
==> Installing facebook/fb/fbsimctl dependency: carthage
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.17.2.el_capitan.bottle.1.tar.gz
Already downloaded: /Users/Dan/Library/Caches/Homebrew/carthage-0.17.2.el_capitan.bottle.1.tar.gz
==> Pouring carthage-0.17.2.el_capitan.bottle.1.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.17.2: 48 files, 11.9M
==> Installing facebook/fb/fbsimctl
==> Downloading https://github.com/facebook/FBSimulatorControl/tarball/v0.1.2
Already downloaded: /Users/Dan/Library/Caches/Homebrew/fbsimctl-0.1.2.2
==> ./build.sh fbsimctl build /usr/local/Cellar/fbsimctl/0.1.2
Last 15 lines from /Users/Dan/Library/Logs/Homebrew/fbsimctl/01.build.sh:

using target fbsimctl
using command build
using output directory /usr/local/Cellar/fbsimctl/0.1.2
/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20160826-17302-s0ge/facebook-FBSimulatorControl-565899f/fbsimctl /private/tmp/fbsimctl-20160826-17302-s0ge/facebook-FBSimulatorControl-565899f
dyld: lazy symbol binding failed: Symbol not found: __TIFC11CarthageKit7Project44buildCheckedOutDependenciesWithConfigurationFTSS19dependenciesToBuildGSqGSaSS__12forPlatformsGVs3SetOS_8Platform_9toolchainGSqSS_15derivedDataPathGSqSS_9sdkFilterFT4sdksGSaOS_3SDK_6schemeSS13configurationSS7projectOS_14ProjectLocator_GO6Result6ResultGSaS3__OS_13CarthageError__GV13ReactiveCocoa14SignalProducerGS9_GO12ReactiveTask9TaskEventTS4_SS__S7__S7__A4_
  Referenced from: /usr/local/opt/carthage/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/CarthageKit

dyld: Symbol not found: __TIFC11CarthageKit7Project44buildCheckedOutDependenciesWithConfigurationFTSS19dependenciesToBuildGSqGSaSS__12forPlatformsGVs3SetOS_8Platform_9toolchainGSqSS_15derivedDataPathGSqSS_9sdkFilterFT4sdksGSaOS_3SDK_6schemeSS13configurationSS7projectOS_14ProjectLocator_GO6Result6ResultGSaS3__OS_13CarthageError__GV13ReactiveCocoa14SignalProducerGS9_GO12ReactiveTask9TaskEventTS4_SS__S7__S7__A4_
  Referenced from: /usr/local/opt/carthage/bin/carthage
  Expected in: /Library/Frameworks/CarthageKit.framework/CarthageKit

./build.sh: line 15: 17317 Trace/BPT trap: 5       carthage bootstrap --platform Mac

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/facebook/homebrew-fb/issues

--------------------------------------------------------------------------------------------------------------------------------------------

I'm having issues installing this, seeing the above error. It correctly fetches carthage, but then fails to find a symbol within the required version when building fbsimctl. Any ideas?

**Comment by lawrencelomax** [comment]
Did you install `carthage` with the both the [`pkg` and with `homebrew`](https://github.com/Carthage/Carthage#installing-carthage)? If it's linking the Swift Runtime that come from two different compiles of Swift, then there will be a mismatch with the Symbols. When I run `carthage` it links a `CarthageKit` that is installed in Homebrew's `/usr/local/Cellar`.

**Comment by DNCGraef** [comment]
Yes! This was exactly the problem - thanks for your help 👍
