### ISSUE TITLE
Building fails due to implicit declaration of function .... 

### ISSUE THREAD

**Issue by matthewc13** [facebook/FBSimulatorControl#314]
Trying to build both from terminal and in Xcode generates the same issue.

"Implicit declaration of function 'object_setClass' is invalid in C99 " 

Apologies if this is a non-issue / a noob problem, but any help with this would be much appreciated

**Comment by matthewc13** [comment]
Should also add a note that this is in Xcode 8.0

**Comment by matthewc13** [comment]
Reinstalled Xcode from Appstore and now its fine ...

**Comment by lawrencelomax** [comment]
It could be that one of the source files is missing an include of the objective-c runtime headers. I'll take a look. What file is failing to compile?

**Comment by matthewc13** [comment]
@lawrencelomax It was the first class it would hit that used that declaration. However like I said above after reinstalling xcode from the app store and not the GM for 8.0 that I had installed. It was fine. Apologies for wasting your time, this is now marked as closed.
