### ISSUE TITLE
How does the JUnit test reported work ? 

### ISSUE THREAD

**Issue by matthewc13** [facebook/FBSimulatorControl#317]
Trying to use the Junit test reporter however given a path it does not write to that location ? Is there something you need to call on it to actually write the file? 

Also can you create a composite test reporter from test reporters and create a Junit test reporter from the composite? Or is this asking for too much :D

**Comment by plu** [comment]
> Trying to use the Junit test reporter however given a path it does not write to that location ? Is there something you need to call on it to actually write the file?

Just pass the JUnit reporter instance down to `startTestWithLaunchConfiguration:reporter:` and it should write the file once the tests have finished. You can look at an example here:

https://github.com/facebook/FBSimulatorControl/blob/1761ad9e7957d952d6a9f6b2bd96865016def6e7/FBSimulatorControlTests/Tests/Integration/FBSimulatorTestInjectionTests.m#L90

> Also can you create a composite test reporter from test reporters and create a Junit test reporter from the composite? Or is this asking for too much :D

I'm not sure I'm understanding the question correctly. `FBSimulatorInteraction` supports setting one test reporter when executing the tests via `startTestWithLaunchConfiguration:reporter:`. This is when `FBTestManagerTestReporterComposite` comes in handy: You can compose several test reporters into a single one and use it when executing the tests. All reporters that were added to the composite one will be called for the methods defined in the `FBTestManagerTestReporter` interface/protocol.

**Comment by matthewc13** [comment]
Ok I am using the JUnit reporter correctly then, its probably a side effect of some of my implementation decisions. 

As for the composite that makes more sense it acts more of a proxy to multiple reporters rather than a traditional "Composite Object". 

Again thanks a lot for your help with this! 

I am working on a hack week project here at work and this tools already got my test times down from 16 mins to 3.5 mins. 

Closing ticket as questions have been sufficiently answered!
