### ISSUE TITLE
Install.md instructions wrong

### ISSUE THREAD

**Issue by bootstraponline** [facebook/FBSimulatorControl#319]
```
$ ./build.sh cli build output
using target cli
using command build
using output directory output
Unknown Command cli
```

**Comment by plu** [comment]
Try this instead: `./build.sh fbsimctl build output`

I've created a pull request to update the documentation.

**Comment by lawrencelomax** [comment]
@bootstraponline  Looks like your PR will fix this issue, Thanks!

Closing now as this will be fixed in the PR.
