### ISSUE TITLE
Doesn't compile with Xcode 7.3.1

### ISSUE THREAD

**Issue by bootstraponline** [facebook/FBSimulatorControl#322]
I'm running the build command as defined in [homebrew-fb/fbsimctl.rb](https://github.com/facebook/homebrew-fb/blob/master/fbsimctl.rb). The code doesn't compile.

```
$ xcodebuild -version
Xcode 7.3.1
Build version 7D1014
```

```
$ ./build.sh fbsimctl build output
```
[fbsimctl build output.txt](https://gist.github.com/bootstraponline/d6adcf22538bb27ba4ea8fe0278133c6)

**Comment by bootstraponline** [comment]
> When building `fbsimctl`, you must be using Xcode 7.1 or greater. Building with Xcode 8 is currently not supported

^ I'm guessing the install docs are wrong?

**Comment by lawrencelomax** [comment]
Yep, the docs are out of date.

`FBSimulatorControl` and other associated Objective-C Frameworks should build and run fine on 7.3.1. `fbsimctl` is restricted to Xcode 8 by virtue of the fact it relies on Swift and therefore a specific swift version.

Having said that, you can still compile `fbsimctl` against Xcode 8 and *run* it against Xcode 7.3.1. If you `xcode-select` an Xcode 7, you should still be able to use it.
