### ISSUE TITLE
Unable to test app once I start WebDriverAgent with fbsimctl

### ISSUE THREAD

**Issue by wuming-eb** [facebook/FBSimulatorControl#324]
I've been able to boot a simulator and install the app I want to test on it, and I'm able to start WDA with simctl as well. These are the commands I'm using
Booting and installing : 
`fbsimctl 'iPhone 6' 'iPhone 6s' 'iOS 10.0' boot --scale=25 -- install $APP_PATH`

Running WDA:
`fbsimctl --state=booted 'iPhone 6' \`
`launch_xctest path/to/WebDriverAgentRunner.xctest $BUNDLE_ID --port 8101 -- \`
`listen`

Once I run that command, I can see the app launch, but it is immediately backgrounded.  WDA seems to be running fine as I can use http://localhost:8101 to inspect the homescreen, but if I open the app, the inspector can't get any of the elements 
![image](https://cloud.githubusercontent.com/assets/22621899/19500956/9162b618-9556-11e6-9357-f12c02e36451.png)

If I use the following: 
`curl -X POST -d '{"desiredCapabilities": {"bundleId": "com.eb.appbeta"}}' 'http://localhost:8101/session'`
It just hangs until the connection times out.

If I run WDA through xcodebuild and then install the app via fbsimctl, it works fine.  Do you have any pointers? Also is this the right place to ask this question?

**Comment by wuming-eb** [comment]
I just realized that the test hosting app shouldn't be the same as the tested app. Closing the issue as it's working now.

**Comment by lawrencelomax** [comment]
Good to hear that it's working for you.
