### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by 778477** [facebook/FBSimulatorControl#327]
i create a new project by Xcode 8.1.

it's a Command Line Tool macOS Application. like fbsimctl

i read the README Installation part. but Running has a Crash:
```

dyld: Library not loaded: @rpath/FBControlCore.framework/Versions/A/FBControlCore
  Referenced from: ~/Library/Developer/Xcode/DerivedData/tmsimctl-deazkozeytfykggtjrotzggmpdud/Build/Products/Debug/tmsimctl
  Reason: image not found
```

**Comment by lawrencelomax** [comment]
Are you copying the `FBSimulatorControl` framework alongside the executable? Command line utilities aren't bundles like Applications, so you can't embed the `FBSimulatorControl` framework alongside the cli executable. The cli is failing because it can't locate `FBSimulatorControl` framework.
