### ISSUE TITLE
iOS10 devices -  Timeout establishing connection

### ISSUE THREAD

**Issue by testobjectnishant** [facebook/FBSimulatorControl#341]
I am using:
OsX El Cap : 10.11.6 (15G1108)
XCode Version 8.0 (8A218a)

On iOs9, it opens the application and stays on application screen and also runs the test.
On iOs10, it opens the application and immediately minimising the application and after sometime it gives following error:

> Error: Error Domain=com.facebook.XCTestBootstrap Code=0 "Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}" UserInfo={NSLocalizedDescription=Test Manager Connection Failed: Internal Error Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}, NSUnderlyingError=0x10d47fe70 {Error Domain=com.facebook.XCTestBootstrap Code=0 "Timeout establishing connection" UserInfo={NSLocalizedDescription=Timeout establishing connection}}}

I think problem is in following code:

> NSDictionary *options = @{@"StartSuspendedKey" : @NO};
> 
> SEL aSelector = NSSelectorFromString(@"launchSuspendedProcessWithDevicePath:bundleIdentifier:environment:arguments:options:");
> 
> NSNumber *PID = [self executeHubProcessControlSelector:aSelector error:error arguments:remotePath, configuration.bundleID, configuration.environment, configuration.arguments, options, nil];

I am passing following values for the selector:

> launchSuspendedProcessWithDevicePath:bundleIdentifier:environment:arguments:options:

```
Bundle ID: com.testobject.IntegrationApp, 
Environment : {
    AppTargetLocation = "/private/var/containers/Bundle/Application/4B50826B-CCD2-47AE-9DF2-6923FD148BA3/IntegrationApp.app/IntegrationApp";
    "DYLD_FRAMEWORK_PATH" = "/private/var/mobile/Containers/Data/Application/7BE15634-C490-4055-8D65-5C1CF13412F1/tmp";
    "DYLD_INSERT_LIBRARIES" = "/private/var/mobile/Containers/Data/Application/7BE15634-C490-4055-8D65-5C1CF13412F1/tmp/IDEBundleInjection.framework/IDEBundleInjection";
    "DYLD_LIBRARY_PATH" = "/private/var/mobile/Containers/Data/Application/7BE15634-C490-4055-8D65-5C1CF13412F1/tmp";
    "OBJC_DISABLE_GC" = YES;
    TestBundleLocation = "/Users/techflitter/Desktop/Apps/TestObjectRunner.xctest";
    XCInjectBundle = "/Users/techflitter/Desktop/Apps/TestObjectRunner.xctest";
    XCInjectBundleInto = "/private/var/containers/Bundle/Application/4B50826B-CCD2-47AE-9DF2-6923FD148BA3/IntegrationApp.app/IntegrationApp";
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/7BE15634-C490-4055-8D65-5C1CF13412F1/tmp/TestPlans/TestObjectRunner.xctest.xctestconfiguration";
}, 

Arguments: (
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
), 

Options: {
    StartSuspendedKey = 0;
}

```

If I do not pass following value:

> "DYLD_INSERT_LIBRARIES" = "/private/var/mobile/Containers/Data/Application/7BE15634-C490-4055-8D65-5C1CF13412F1/tmp/IDEBundleInjection.framework/IDEBundleInjection";

Application opens properly on both iOs9 and iOS10 devices but it still gives timeout error.

**Comment by marekcirkos** [comment]
Is this device or simulator? Your logs are a bit confusing.

**Comment by testobjectnishant** [comment]
Its a device. I started the test using following method:
`- (nullable FBTestManager *)startTestManagerWithAttributes:(NSArray<NSString *> *)attributes environment:(NSDictionary<NSString *, NSString *> *)environment error:(NSError **)error`

**Comment by marekcirkos** [comment]
This method does not support iOS 10 devices, because it depends on code injection. Apple blocked that on iOS 10 devices.

**Comment by testobjectnishant** [comment]
@marekcirkos can you please guide me how to do it for iOS10 devices ?

**Comment by marekcirkos** [comment]
@testobjectnishant Unfortunately for the time being you can use `xcodebuild`.

**Comment by aluedeke** [comment]
@marekcirkos assuming we compile a ipa which has xctest bundle and xctest framework and probably xctest config already build in it would work right?

**Comment by testobjectnishant** [comment]
@marekcirkos can we directly launch WebDriverAgentRunner application with required environment variables and arguments ?

**Comment by marekcirkos** [comment]
`xcodebuild` has `test-without-building` option that you should have a look at. Alternatively you can check this out https://github.com/facebook/FBSimulatorControl/blob/master/FBDeviceControl/Strategies/FBDeviceTestRunStrategy.m

**Comment by testobjectnishant** [comment]
yeah, that is the last possible option :(
