### ISSUE TITLE
Class _X is implemented in both /usr/local... and /Applications/XCode.app...

### ISSUE THREAD

**Issue by lanzelot1989** [facebook/FBSimulatorControl#361]
Hi!

Similarly to this issue #https://github.com/plu/pxctest/issues/1 I get a message that several classes are implemented in both the Homebrew directory and the XCode directory.

The output is generated before every command I execute with fbsimctl.

Is there a possibility to overcome this?

**Comment by plu** [comment]
Which version of `pxctest`, Xcode and Homebrew do you have?

**Comment by lanzelot1989** [comment]
Tried Fbsimctl with head and 0.2.2, XCode is up-to-date (8.2.1).

**Comment by LeoNatan** [comment]
Yes, getting this also.

**Comment by sleekweasel** [comment]
I get a crash:

$ fbsimctl list
objc[77330]: Class _TtCs18_EmptyArrayStorage is implemented in both /usr/local/Cellar/fbsimctl/0.2.2/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib. One of the two will be used. Which one is undefined.
...
2017-01-23 14:43:11.994 fbsimctl[77330:1914183] *** Assertion failure in -[FBSimulatorConfiguration initWithNamedDevice:os:auxillaryDirectory:], /tmp/fbsimctl-20170123-75889-4ozuo4/facebook-FBSimulatorControl-f41dec3/FBSimulatorControl/Configuration/FBSimulatorConfiguration.m:32
2017-01-23 14:43:11.995 fbsimctl[77330:1914183] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: os'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9628b4f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8fddef7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff962901ca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff91565856 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   FBSimulatorControl                  0x000000010369ea04 -[FBSimulatorConfiguration initWithNamedDevice:os:auxillaryDirectory:] + 676
	5   FBSimulatorControl                  0x000000010369ec4f __48+[FBSimulatorConfiguration defaultConfiguration]_block_invoke + 127
	6   libdispatch.dylib                   0x00007fff9314240b _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00007fff93142303 dispatch_once_f + 67
	8   FBSimulatorControl                  0x000000010369eba4 +[FBSimulatorConfiguration defaultConfiguration] + 84
	9   FBSimulatorControl                  0x00000001036db4ae +[FBSimulatorConfiguration(CoreSimulator) inferSimulatorConfigurationFromDevice:error:] + 878
	10  FBSimulatorControl                  0x00000001036d2675 +[FBSimulator fromSimDevice:configuration:launchdSimProcess:containerApplicationProcess:set:] + 309
	11  FBSimulatorControl                  0x00000001036d5047 -[FBSimulatorInflationStrategy inflateSimulators:availableDevices:previouslyIdentifiedContainerApplications:] + 1063
	12  FBSimulatorControl                  0x00000001036d4b39 -[FBSimulatorInflationStrategy inflateFromDevices:exitingSimulators:] + 1161
	13  FBSimulatorControl                  0x00000001036a8fc1 -[FBSimulatorSet allSimulators] + 145
	14  FBSimulatorControl                  0x00000001036a69c2 -[FBSimulatorSet query:] + 162
	15  FBSimulatorControlKit               0x00000001034ec619 _TFV21FBSimulatorControlKit16iOSRunnerContext5queryfCSo16FBiOSTargetQueryGSaPSo11FBiOSTarget__ + 505
	16  FBSimulatorControlKit               0x00000001034f9e5e _TFV21FBSimulatorControlKit10ListRunner3runfT_OS_13CommandResult + 622
	17  FBSimulatorControlKit               0x00000001034f3da2 _TFV21FBSimulatorControlKit12ActionRunner3runfT_OS_13CommandResult + 6514
	18  FBSimulatorControlKit               0x00000001034ef40f _TFV21FBSimulatorControlKit13CommandRunner3runfT_OS_13CommandResult + 6191
	19  FBSimulatorControlKit               0x00000001034ed675 _TFV21FBSimulatorControlKit17BaseCommandRunner3runfT_OS_13CommandResult + 2549
	20  FBSimulatorControlKit               0x0000000103430969 _TFV21FBSimulatorControlKit9CLIRunner3runfT_OS_13CommandResult + 1257
	21  FBSimulatorControlKit               0x000000010342fa7a _TFV21FBSimulatorControlKit9CLIRunner12runForStatusfT_Vs5Int32 + 42
	22  FBSimulatorControlKit               0x000000010342f516 _TZFC21FBSimulatorControlKit15CLIBootstrapper9bootstrapfT_Vs5Int32 + 2390
	23  FBSimulatorControlKit               0x0000000103430399 _TToZFC21FBSimulatorControlKit15CLIBootstrapper9bootstrapfT_Vs5Int32 + 25
	24  fbsimctl                            0x000000010341c568 main + 56
	25  libdyld.dylib                       0x00007fff8662c5ad start + 1
	26  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by lanzelot1989** [comment]
Hi guys!

I wanted to push this again, is there a fix for this or should there be no negative side effects for the described output?

**Comment by LeoNatan** [comment]
With the latest version of fbsimctl (built using `--HEAD`) and latest Xcode 8.3 build, this issue seems fixed.

**Comment by lanzelot1989** [comment]
@LeoNatan Yeah, works for me too now

**Comment by aroswell** [comment]
I'm having this issue with the latest xcodebuild and fbsimctl. What was the fix?

» xcodebuild -version                                                         
Xcode 8.3.2
Build version 8E2002

» fbsimctl list                                                              
objc[62972]: Class _TtCs18_EmptyArrayStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-41633fc/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x1089e3990) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10c561990). One of the two will be used. Which one is undefined.

**Comment by vathsalahn** [comment]
Is this issue fixed?? Even i am facing this issue now

**Comment by marekcirkos** [comment]
@vathsalahn You should raise this issue on fbsimctl repo

**Comment by kahyalar** [comment]
I'm having this issue too. 
XCode - 8.3.3
fbsimctl - --HEAD

ERROR:
fbsimctl list

objc[46185]: Class _TtCs18_EmptyArrayStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fa990) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937990). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs20_RawNativeSetStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9faa40) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937a40). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17_CocoaSetIterator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa0fa98) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d94ca98). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs27_RawNativeDictionaryStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fab08) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937b08). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs24_CocoaDictionaryIterator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa10a98) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d94da98). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17NonObjectiveCBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa12538) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d94f538). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17_stdlib_AtomicInt is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa149a8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9519a8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs19_SwiftNativeNSArray is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fabe0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937be0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs24_SwiftNativeNSDictionary is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fac48) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937c48). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17_SwiftNativeNSSet is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9facb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937cb0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs24_SwiftNativeNSEnumerator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fad18) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937d18). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs18_SwiftNativeNSData is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fad80) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937d80). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs26_SwiftNativeNSCharacterSet is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fade8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937de8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs31_stdlib_ReturnAutoreleasedDummy is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fae50) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937e50). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs20_SwiftNativeNSString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9faec8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937ec8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs19_NSContiguousString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9faf30) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937f30). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs40_SwiftNativeNSArrayWithContiguousStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fafb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937fb0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs21_SwiftDeferredNSArray is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb020) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938020). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs27_ContiguousArrayStorageBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb0b0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9380b0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs14_VaListBuilder is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa19ec0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d956ec0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs13VaListBuilder is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa19fb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d956fb0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSError is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb148) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938148). One of the two will be used. Which one is undefined.
objc[46185]: Class SwiftObject is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb198) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938198). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftValue is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb210) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938210). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNull is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb260) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938260). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSArrayBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb2b0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9382b0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSDictionaryBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb300) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938300). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSSetBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb350) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938350). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSStringBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb3a0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9383a0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSEnumeratorBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb3f0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9383f0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSDataBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb440) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938440). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSCharacterSetBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb490) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938490). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSIndexSetBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb4e0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9384e0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC8Dispatch16DispatchWorkItem is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftDispatch.dylib (0x10ad5be58) and /Applications/Xcode.app/Contents/Frameworks/libswiftDispatch.dylib (0x10dc4ee58). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation20_SwiftNSCharacterSet is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8bac0) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd7dac0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation12_DataStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f058) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81058). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation12_NSSwiftData is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8bb60) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd7db60). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation25_NSErrorRecoveryAttempter is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f690) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81690). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation25NSFastEnumerationIterator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f730) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81730). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation15NSSimpleCString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f7e8) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd817e8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation16NSConstantString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f878) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81878). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftTypePreservingNSNumber is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8bc18) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd7dc18). One of the two will be used. Which one is undefined.
FE551EBD-602E-496A-A41A-1C8FC96742E8 | iPad Pro (9.7 inch) | Shutdown | iPad Pro (9.7-inch) | iOS 10.3 | x86_64
E03D64E2-D8C0-406C-A7F5-5A8F8F921721 | iPad Pro (12.9 inch) | Shutdown | iPad Pro (12.9-inch) | iOS 10.3 | x86_64
90ACDA8E-4B73-4C95-92AD-2CAD8377D021 | iPad Air 2 | Shutdown | iPad Air 2 | iOS 10.3 | x86_64
2C19B1D4-4D6E-4503-9948-658B52A07091 | iPad Air | Shutdown | iPad Air | iOS 10.3 | x86_64
0FB07058-F6C7-43A6-B6C3-CAD78003505B | iPhone SE | Shutdown | iPhone SE | iOS 10.3 | x86_64
839100EE-906D-45FD-BC0E-0C47A79CE14F | iPhone 7 Plus | Shutdown | iPhone 7 Plus | iOS 10.3 | x86_64
C26E3F29-09D3-4970-80B9-154CE68F355E | iPhone 7 | Shutdown | iPhone 7 | iOS 10.3 | x86_64
147E64A7-2E07-40B7-8DE6-16FB906E8A1F | iPhone 6s Plus | Shutdown | iPhone 6s Plus | iOS 10.3 | x86_64
202ED520-302E-4040-97EE-60657B9F756F | iPhone 6s | Shutdown | iPhone 6s | iOS 10.3 | x86_64
333C0646-A025-48D7-B345-CD203F8914CD | iPhone 6 Plus | Shutdown | iPhone 6 Plus | iOS 10.3 | x86_64
1FA0D835-601F-4929-9963-A3C367BDCA7B | iPhone 6 | Shutdown | iPhone 6 | iOS 10.3 | x86_64
E30B5606-FAF7-4E39-B0DA-91587B4076E1 | iPhone 5s | Shutdown | iPhone 5s | iOS 10.3 | x86_64
86346D4F-837A-4906-B5B7-610D7759123D | iPhone 5 | Shutdown | iPhone 5 | iOS 10.3 | i386
7E495B80-A72F-41EE-ABDA-7A70BBD9D541 | Apple TV 1080p | Shutdown | Apple TV 1080p | tvOS 10.2 | x86_64
09CB7345-53B1-41A2-8A34-A34F4BE2101E | Apple Watch Series 2 - 42mm | Shutdown | Apple Watch Series 2 - 42mm | watchOS 3.2 | i386
5A8A67B1-8EC1-4475-9DA6-80BC92AF2191 | Apple Watch Series 2 - 38mm | Shutdown | Apple Watch Series 2 - 38mm | watchOS 3.2 | i386
8DB08BF3-B4F6-4405-BD4E-89E96BDFB1CB | Apple Watch - 42mm | Shutdown | Apple Watch - 42mm | watchOS 3.2 | i386
348A2EFD-4C6A-430E-9B74-3A5E338059FD | Apple Watch - 38mm | Shutdown | Apple Watch - 38mm | watchOS 3.2 | i386
F4CF2A6D-EBBB-4A2F-807D-6C7158BE2A96 | iPad Pro (10.5-inch) | Shutdown |
5020B4CE-27E1-4880-B396-9F2DB17509BF | iPad Pro (12.9-inch) (2nd generation) | Shutdown |
3438CC29-B973-41DE-B170-6A2F5E3EA4E7 | iPad (5th generation) | Shutdown |
