### ISSUE TITLE
Integration with Appium

### ISSUE THREAD

**Issue by garyodonoghue** [facebook/FBSimulatorControl#364]
Hey guys, 

With Appium 1.6.0 supporting [the running of XCUITests](https://github.com/appium/appium/releases/tag/v1.6.0), does that mean this tool could be leveraged in order to run an Appium test suite across multiple simulators? 

Thanks in advance

**Comment by saikrishna321** [comment]
@garyodonoghue appium does not use fbsimctl  in the latest. So you can't run multiple simulators using appium

**Comment by garyodonoghue** [comment]
Thanks for your comment, my query would maybe be more appropriate on an Appium forum so, as I'd be interested to know what would be required to have use fbsimctl for executing its test suite, thanks

**Comment by saikrishna321** [comment]
@garyodonoghue yah this should be raised on appium forum. There is a PR for that same.

FYI https://github.com/appium/node-simctl/pull/28

**Comment by garyodonoghue** [comment]
Great stuff, thanks @saikrishna321 ! Looks like there's still plenty left to do in order to have this running as part of the overall Appium framework, with this PR being the first step in that process if I understand it correctly, but it'll be interesting to see it progress and develop. Closing this out, thanks for your help again
