### ISSUE TITLE
CLI exits with timeout error when booting iOS 8.1 on macOS 10.12

### ISSUE THREAD

**Issue by AndreyBelym** [facebook/FBSimulatorControl#368]
If you try to start iOS 8.1 device e.g. iPhone 4s on macOS 10.12 Siera. `fbsimctl` will successfully start the simulator, and then will hang for some time (about a couple of minutes) and will exit with the following error:
```
Error Domain=com.facebook.FBSimulatorControl Code=0 "Timed out waiting for all required services [com.apple.SpringBoard, com.apple.medialibraryd, com.apple.backboardd, com.apple.mobile.installd, com.apple.SimulatorBridge] to start" UserInfo={NSLocalizedDescription=Timed out waiting for all required services [com.apple.SpringBoard, com.apple.medialibraryd, com.apple.backboardd, com.apple.mobile.installd, com.apple.SimulatorBridge] to start}
```

**Comment by dig412** [comment]
Is this because some of those services don't exist on iOS < 9?

This seems to imply that 'com.apple.backboardd' and 'com.apple.medialibraryd' are missing:
https://github.com/plu/simctl/blob/master/lib/simctl/device.rb#L260

**Comment by AndreyBelym** [comment]
To be precise, `com.apple.medialibraryd` don't run on iOS 8.1, `com.apple.backboardd` is okay.

**Comment by lawrencelomax** [comment]
if that's the case it should be pretty easy to adjust the list of required services to verify a sim is booted, based on the OS Version. This should be a simple PR, if anyone wants to put one up.

**Comment by lawrencelomax** [comment]
The underlying issue looks to be fixed with the PR. Considering this closed. Reopen if there are any further issues.
