### ISSUE TITLE
`fbsimctl install` crashes and never installs the app

### ISSUE THREAD

**Issue by rotemmiz** [facebook/FBSimulatorControl#373]
This started happening after [this commit](https://github.com/facebook/FBSimulatorControl/commit/99b97da4306c87f6d88cecd48a753c53e5b3e654) was introduced.

Error log (not much in it):
```fbsimctl --json 9464677E-9962-4C3B-91E8-C969B6337A68 install /Users/travis/build/wix/detox/detox/test/ios/build/Build/Products/Release-iphonesimulator/example.app` (exited with error code null)```

complete log at: https://travis-ci.org/wix/detox/builds/199141501#L2279

I think the way of Installing fbsimctl with `brew install fbsimctl --HEAD` is too fragile ,and there's no way of specifying a version since there were no releases since October :( 

Are there any plans to start releasing versions in the future ?
Thanks!

**Comment by lawrencelomax** [comment]
> Are there any plans to start releasing versions in the future?

I have tended to do this in the past when there are breaking changes that require a modification of the `homebrew` formula. Otherwise I don't tend to do it as I haven't automated it yet 😜.

Can you provide output with `--debug-logging` enabled? I'm keen to get this fixed if this is affecting you.

**Comment by lawrencelomax** [comment]
Actually, I can repro this locally. Will see if I can get a fix going.

**Comment by lawrencelomax** [comment]
cc @zsol

**Comment by plu** [comment]
https://github.com/plu/FBSimulatorControl/commit/68351498e669dfa9fa2da728bc6adb581bca183f might be related, part of #372.

**Comment by lawrencelomax** [comment]
@plu can you pull in the change to a separate PR. Will be easier for me to get merged ASAP.
