### ISSUE TITLE
Can WDA be launched on 2 real iPhones using fbsimctl?

### ISSUE THREAD

**Issue by vathsalahn** [facebook/FBSimulatorControl#382]
I was using xcodebuild to run the testcases but always it picks up the port 8100.Can fbsimctl allows to launch WDA on 2 real iPhones on different ports ??

**Comment by wacban** [comment]
The wda server is running on the phone so if you start it on two iphones the IP addresses will be different - you shouldn't need to set different port. 
That being said it is possible to set different port using --port.
