### ISSUE TITLE
Kill reparented xcodebuild processes for a Device on the next test-run invocation

### ISSUE THREAD

**Issue by vathsalahn** [facebook/FBSimulatorControl#384]
1. Tried to start WDA on the iphone using the below command
- fbsimctl $device_id launch_xctest <path_to_WDA>/WebDriverAgentRunner.xctest <path_to_WDA>/WebDriverAgentRunner-Runner.app  --port 8101 -- listen
Launched the Unit Tests Successfully
2.Terminated The test by sending CTRL+c.
3.Relaunched the WDA using the same fbsimctl command but the tests fails with following error
Test Suite 'Selected tests' failed at 2017-02-22 16:11:22.538.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.011) seconds, NSLocalizedDescription=Returned non-zero status code 65}}}

4.This issue occurs alternatively(odd iterations -- Passed,Even Iterations -- Failed).

**Comment by wacban** [comment]
There is a known issue that may be causing this - fbsimctl doesn't kill xcodebuild when killed. 
Can you try killing the xcodebuild process between runs? 

If it doesn't help, can you run fbsimctl with NSUnbufferedIO=YES like that:
NSUnbufferedIO=YES fbsimctl $device_id ...
and paste the results here please?

**Comment by vathsalahn** [comment]
NSUnbufferedIO=YES fbsimctl $device_id cmd ... did not solve the problem. So killing the xcodebuild process explicitly works fine.

Thank you :)

**Comment by lawrencelomax** [comment]
I just spoke with @wacban and we could use a strategy for killing a prior `xcodebuild` invocation *before* running the next invocation of `xcodebuild`. We do something similar with `Simulator.app`, to keep track of which `Simulator.app` has booted by UDID. @wacban also suggested a signal handler for killing `xcodebuild` subprocesses so that they aren't reparented when `fbsimctl` dies.

**Comment by lawrencelomax** [comment]
@vathsalahn let me know if the recent commits have helped you here. We now have logic for killing `xcodebuild` processes that have been reparented from a previous run.

**Comment by vathsalahn** [comment]
Yes it works fine .. :)

**Comment by lawrencelomax** [comment]
Great, thanks!
