### ISSUE TITLE
Streaming simulator screen

### ISSUE THREAD

**Issue by ssynix** [facebook/FBSimulatorControl#389]
Hey!

I'm trying to stream a simulator's screen using `FBSimulatorControl`, but being new to Objective-C and all, I'm finding myself quite lost in the `FBFrameBuffer*` classes.

At first, I just added some code in `FBFramebufferVideo` to compress and send out the frames as they came–admittedly a very hacky implementation. It seems like using `SimDisplayVideoWriter` you no longer deal with individual frames anymore?

What I'm thinking is either repeatedly taking screenshots the same way `fbsimctl` does, or figuring out a way to piggyback on the `FBFramebufferSurfaceClient` and `FBFramebufferFrameSink` implementations to accomplish something similar. I care more about performance than frame rate if it helps (10 FPS is fine).

I'd appreciate it if you could point me in the right direction!

**Comment by lawrencelomax** [comment]
Hello!

I'm currently investigating this area. You're absolutely right that we switched the video encoder for Apple's implementation. The current implementation is focused on writing to files, but that is just how things stand currently and not a representation of how I want the API to be in future.

Apple's Frameworks (and simctl) now support writing Fragmented MP4 to a socket or stdout, but this isn't currently low-latency enough to be used for live streaming. 

I'll update this thread with more information shortly, including how you might use this in a video pipeline.

**Comment by ssynix** [comment]
I'd rather stay away from video files as much as possible. I ran into a lot of complications doing that in my initial approach, but had pretty decent results just sending ~10/sec low-quality jpeg files over websockets. Also the latency issue that you mentioned.

Looking forward to your update!

**Comment by lawrencelomax** [comment]
bf0f6e has made a public API for connecting clients to the Framebuffer. It should now be possible to receive either raw Frames, or to add a `IOSurface` sink. I hope to add inbuilt implementations for streaming in future.

**Comment by lawrencelomax** [comment]
There are a number of recent improvements here. There's a special `fbsimctl stream` command that supports streaming ARGB Bitmaps over a file or `stdout`. The output of this can be used to drive a video pipeline using other applications.

**Comment by JonGabilondoAngulo** [comment]
Hi,
I'm trying it without success, 

fbsimctl YourDeviceID stream --bgra -|ffmpeg -f h264 -i pipe:0 -vcodec copy -tune zerolatency -b 900k -f mpegts udp://127.0.0.1:12345

fbsimctl seems to advance but I get no connection to the UDP address using VLC viewer.
Anyone with more luck ?
Thanks

**Comment by stoefln** [comment]
Would be interested too!
