### ISSUE TITLE
fbsimctl crash

### ISSUE THREAD

**Issue by yaphatak** [facebook/FBSimulatorControl#394]
@lawrencelomax : Have you seen such crashes? We try to launch multiple simulators. When I do this manually via terminal it works fine. But when I put this under our service , basically only change we did is started used `direct-launch` instead of plain boot. 

Here is crash [log](https://gist.github.com/yaphatak/eba6468b87ec0f99f1e6a8ddae6b0168)

**Comment by zsol** [comment]
Is your service closing stdout or stderr before execing fbsimctl?

**Comment by yaphatak** [comment]
@zsol When you said close `stdout` or `stderr`, is it the one belongs to earlier `fbsimctl` process? We don't explicitly close it. 
I just tried launching them via mac application (using swift), it works. For some reason it doesn't when using `mono`. I will debug more

**Comment by yaphatak** [comment]
redirecting stdout & stderr to `/dev/null` fixes it
