### ISSUE TITLE
Select by name doesn't seem to work.

### ISSUE THREAD

**Issue by sleekweasel** [facebook/FBSimulatorControl#398]
$ fbsimctl list |grep Grank
    47D58B42-82D9-4E81-AAE7-FF52A1DE35D6 | Grank | Shutdown | iPhone 6 | iOS 10.1
    $ fbsimctl Grank boot
    Failed to Parse Command '["Grank", "boot"]' does not match '[fbsimctl {{ [output] | [management] | --set <directory> }}* [targets]? [target-format]* {{ [action] ... -- [action] }}+

... and then 400 lines of splurge which might be better hidden behind '--help'.

Is 'Grank' not what 

    [targets/query] Target: Queries
    ===============================

        --first <int> | <udid> | --state=creating | --state=shutdown | --state=booting | --state=booted | --state=shutting-down | --arch=i386 | --arch=x86_64 | --arch=armv7 | --arch=armv7s | --arch=arm64 | --simulators | --devices | <os-version> | <device-name>

means by 'name'?

The reason I'm interested in 'name' is because it was supported by simctl and was a convenient way to persist pre-booted simulators without having to maintain an index file mapping udid to worker thread.

Incidentally, 'Grank' was created under fbsimctl, but renamed by 'xcrun simctl rename'.

/usr/local/Cellar/fbsimctl/0.3.0/bin/fbsimctl

Thanks.

**Comment by lawrencelomax** [comment]
"Name" does not mean the user-supplied name that you've provided, but the model of the iPhone. This should probably be clearer as this is currently ambiguous. I've just landed some substantial changes to how a Simulator configuration is considered, so I should be able to augment and disambiguate this with an actual device name.

**Comment by lawrencelomax** [comment]
I'll probably have some changes out next week to add something like `--name=`
