### ISSUE TITLE
Instaling apps on iPhone 5 simulator fails with: Error Domain=Foundation._GenericObjCError Code=0 "(null)"

### ISSUE THREAD

**Issue by b1ueshad0w** [facebook/FBSimulatorControl#403]

**Comment by lawrencelomax** [comment]
This is likely because your app doesn't have the i386 slice that is required of 32 bit simulators. I also have a fix available shortly that will ensure the error is propagated with the appropriate message.

**Comment by b1ueshad0w** [comment]
Seems you are right. Thanks.
