### ISSUE TITLE
fbsimctl record not working when path to file is in quotes

### ISSUE THREAD

**Issue by sergd2005** [facebook/FBSimulatorControl#410]
Hi guys, I am executing same command in terminal with quotes for file path - in that case recording not starting
fbsimctl 9D215DF6-A576-4A2B-B3CC-60C4D4EDAD13 record start "~/Desktop/1.mp4" 
and without quotes - in that case everything works fine
fbsimctl 9D215DF6-A576-4A2B-B3CC-60C4D4EDAD13 record start ~/Desktop/1.mp4
 

Any ideas? is it bug in fbsimctl?

**Comment by plu** [comment]
`fbsimctl` does not expand the `~` for you. Without quotes the shell does that for you. With quotes the program the argument is being passed to has to do it. Example:

```
 ~$ ls -lad ~/Desktop/
drwx------+ 12 joplunien  110185346  408 May 10 12:38 /Users/joplunien/Desktop/

 ~$ ls -lad "~/Desktop/"
ls: ~/Desktop/: No such file or directory
```

Even `ls` fails at that job. So I don't think `fbsimctl` should handle this :).

**Comment by sergd2005** [comment]
Thx
