### ISSUE TITLE
Class _X duplication error

### ISSUE THREAD

**Issue by kahyalar** [facebook/FBSimulatorControl#431]
Hi folks, I'm having this issue.

My ENV 
XCode - 8.3.3
fbsimctl - --HEAD

ERROR:
fbsimctl list

objc[46185]: Class _TtCs18_EmptyArrayStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fa990) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937990). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs20_RawNativeSetStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9faa40) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937a40). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17_CocoaSetIterator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa0fa98) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d94ca98). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs27_RawNativeDictionaryStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fab08) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937b08). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs24_CocoaDictionaryIterator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa10a98) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d94da98). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17NonObjectiveCBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa12538) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d94f538). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17_stdlib_AtomicInt is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa149a8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9519a8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs19_SwiftNativeNSArray is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fabe0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937be0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs24_SwiftNativeNSDictionary is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fac48) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937c48). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs17_SwiftNativeNSSet is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9facb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937cb0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs24_SwiftNativeNSEnumerator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fad18) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937d18). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs18_SwiftNativeNSData is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fad80) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937d80). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs26_SwiftNativeNSCharacterSet is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fade8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937de8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs31_stdlib_ReturnAutoreleasedDummy is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fae50) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937e50). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs20_SwiftNativeNSString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9faec8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937ec8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs19_NSContiguousString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9faf30) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937f30). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs40_SwiftNativeNSArrayWithContiguousStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fafb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d937fb0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs21_SwiftDeferredNSArray is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb020) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938020). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs27_ContiguousArrayStorageBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb0b0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9380b0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs14_VaListBuilder is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa19ec0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d956ec0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtCs13VaListBuilder is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10aa19fb0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d956fb0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSError is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb148) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938148). One of the two will be used. Which one is undefined.
objc[46185]: Class SwiftObject is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb198) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938198). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftValue is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb210) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938210). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNull is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb260) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938260). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSArrayBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb2b0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9382b0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSDictionaryBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb300) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938300). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSSetBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb350) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938350). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSStringBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb3a0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9383a0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSEnumeratorBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb3f0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9383f0). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSDataBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb440) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938440). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSCharacterSetBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb490) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d938490). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftNativeNSIndexSetBase is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x10a9fb4e0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x10d9384e0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC8Dispatch16DispatchWorkItem is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftDispatch.dylib (0x10ad5be58) and /Applications/Xcode.app/Contents/Frameworks/libswiftDispatch.dylib (0x10dc4ee58). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation20_SwiftNSCharacterSet is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8bac0) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd7dac0). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation12_DataStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f058) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81058). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation12_NSSwiftData is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8bb60) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd7db60). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation25_NSErrorRecoveryAttempter is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f690) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81690). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation25NSFastEnumerationIterator is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f730) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81730). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation15NSSimpleCString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f7e8) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd817e8). One of the two will be used. Which one is undefined.
objc[46185]: Class _TtC10Foundation16NSConstantString is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8f878) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd81878). One of the two will be used. Which one is undefined.
objc[46185]: Class _SwiftTypePreservingNSNumber is implemented in both /usr/local/Cellar/fbsimctl/HEAD-f079845/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftFoundation.dylib (0x10ae8bc18) and /Applications/Xcode.app/Contents/Frameworks/libswiftFoundation.dylib (0x10dd7dc18). One of the two will be used. Which one is undefined.
FE551EBD-602E-496A-A41A-1C8FC96742E8 | iPad Pro (9.7 inch) | Shutdown | iPad Pro (9.7-inch) | iOS 10.3 | x86_64
E03D64E2-D8C0-406C-A7F5-5A8F8F921721 | iPad Pro (12.9 inch) | Shutdown | iPad Pro (12.9-inch) | iOS 10.3 | x86_64
90ACDA8E-4B73-4C95-92AD-2CAD8377D021 | iPad Air 2 | Shutdown | iPad Air 2 | iOS 10.3 | x86_64
2C19B1D4-4D6E-4503-9948-658B52A07091 | iPad Air | Shutdown | iPad Air | iOS 10.3 | x86_64
0FB07058-F6C7-43A6-B6C3-CAD78003505B | iPhone SE | Shutdown | iPhone SE | iOS 10.3 | x86_64
839100EE-906D-45FD-BC0E-0C47A79CE14F | iPhone 7 Plus | Shutdown | iPhone 7 Plus | iOS 10.3 | x86_64
C26E3F29-09D3-4970-80B9-154CE68F355E | iPhone 7 | Shutdown | iPhone 7 | iOS 10.3 | x86_64
147E64A7-2E07-40B7-8DE6-16FB906E8A1F | iPhone 6s Plus | Shutdown | iPhone 6s Plus | iOS 10.3 | x86_64
202ED520-302E-4040-97EE-60657B9F756F | iPhone 6s | Shutdown | iPhone 6s | iOS 10.3 | x86_64
333C0646-A025-48D7-B345-CD203F8914CD | iPhone 6 Plus | Shutdown | iPhone 6 Plus | iOS 10.3 | x86_64
1FA0D835-601F-4929-9963-A3C367BDCA7B | iPhone 6 | Shutdown | iPhone 6 | iOS 10.3 | x86_64
E30B5606-FAF7-4E39-B0DA-91587B4076E1 | iPhone 5s | Shutdown | iPhone 5s | iOS 10.3 | x86_64
86346D4F-837A-4906-B5B7-610D7759123D | iPhone 5 | Shutdown | iPhone 5 | iOS 10.3 | i386
7E495B80-A72F-41EE-ABDA-7A70BBD9D541 | Apple TV 1080p | Shutdown | Apple TV 1080p | tvOS 10.2 | x86_64
09CB7345-53B1-41A2-8A34-A34F4BE2101E | Apple Watch Series 2 - 42mm | Shutdown | Apple Watch Series 2 - 42mm | watchOS 3.2 | i386
5A8A67B1-8EC1-4475-9DA6-80BC92AF2191 | Apple Watch Series 2 - 38mm | Shutdown | Apple Watch Series 2 - 38mm | watchOS 3.2 | i386
8DB08BF3-B4F6-4405-BD4E-89E96BDFB1CB | Apple Watch - 42mm | Shutdown | Apple Watch - 42mm | watchOS 3.2 | i386
348A2EFD-4C6A-430E-9B74-3A5E338059FD | Apple Watch - 38mm | Shutdown | Apple Watch - 38mm | watchOS 3.2 | i386
F4CF2A6D-EBBB-4A2F-807D-6C7158BE2A96 | iPad Pro (10.5-inch) | Shutdown |
5020B4CE-27E1-4880-B396-9F2DB17509BF | iPad Pro (12.9-inch) (2nd generation) | Shutdown |
3438CC29-B973-41DE-B170-6A2F5E3EA4E7 | iPad (5th generation) | Shutdown |

**Comment by kahyalar** [comment]
Hello all, a quick update to my issue. When i install it via [this custom installation method](https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/Documentation/Installation.md), and it's gone. But i have issues with "Simulator does not support any of the architectures ([arm, arm64])"

Any helps ? :)

**Comment by plu** [comment]
Looks like your App was built for a device (`arm`, `arm64`) instead of for the Simulator (`i386`, `x86_64 `).

**Comment by kahyalar** [comment]
Hey @plu, 

You are right ! But is only way to achieve on this built a new .app from source code ?
Beacuse i'm currently working on a outsource company and we are not built these apps. We're just testing them.

Do you have any suggestions ? 
Thanks

**Comment by plu** [comment]
Yes, you will need the source code to build it for a different architecture.

**Comment by kahyalar** [comment]
I understand. Thanks for your help ! 👍

**Comment by lawrencelomax** [comment]
This is a problem with Swift runtime overlay conflicts when linking Frameworks embedded in Xcode. It's one of the reasons we've removed this dependency and aren't looking to add any more Swift to the project until ABI stability for Swift is out.

Basically:
1) `fbsimctl` links version X of Swift, with the dylib runtime overlays.
2) `FBSimulatorControl` or `FBDeviceControl` linked an Xcode private framework that uses the runtime overlays of version Y of Swift
3) Symbol duplication crash.

This should now be fixed because we're limiting the the private frameworks that we link to be as minimal as possible. When Swift is ABI-stable in future we'll this will no longer happen in future.
