### ISSUE TITLE
[Question] Possible to shutdown one simulator at a time?

### ISSUE THREAD

**Issue by blakeprobinson** [facebook/FBSimulatorControl#448]
Hi,

I read in the documentation that the command, "fbsimctl shutdown," will shutdown all booted simulators.  Is it possible to pass this command a simulator id, for example, to make the command apply to just one booted simulator?  If this is not possible, is it possible to make the command, "fbsimctl install SomeApp.app," apply to just one booted simulator?

Thanks!

**Comment by NickAb** [comment]
You can just specify list of UDIDs of simulators you want to shutdown
```bash
# shutdown one simulator by UDID
fbsimctl F0F071BB-8775-472C-8378-262BB6D31212 shutdown
# shutdown multiple simulators by UDID
fbsimctl F0F071BB-8775-472C-8378-262BB6D31212 044668F4-D4A6-49BC-8D56-F45B58314A7F shutdown
```

Same applies to `install` command and many other commands.

https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/README.md

**Comment by blakeprobinson** [comment]
Many thanks for your response.
