### ISSUE TITLE
Unable to install fbsimctl

### ISSUE THREAD

**Issue by pgodbole01** [facebook/FBSimulatorControl#452]
Hi,

I am trying to install fbsimctl with configuration X-Code 9 and OS version 10.13 High Sierra, but it is not installing. I tried previously for X-Code 8 and at that time it works. But now it is not working.

I am getting following error - 

/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20171005-23479-1tm9r51/fbsimctl /private/tmp/fbsimctl-20171005-23479-1tm9r51
*** Skipped installing GCDWebServer.framework binary due to the error:
	"GitHub API request failed: jsonDecodingError(Multiple(TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null), TypeMismatch(Expected Object, got Null)))"
*** Checking out GCDWebServer at "3.3.3"
A shell task (/usr/bin/env git checkout --quiet --force 3.3.3 (launched in /Users/pgodbole/Library/Caches/org.carthage.CarthageKit/dependencies/GCDWebServer)) failed with exit code 128:
fatal: Unable to create '/Users/pgodbole/Library/Caches/org.carthage.CarthageKit/dependencies/GCDWebServer/index.lock': Operation not permitted

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/facebook/homebrew-fb/issues

I checked by trying to listing devices associated to fbsimctl, but not working. Please help with this problem as I want to setup an automation.

**Comment by vincentkjj** [comment]
I am seeing the same issue with Xcode 9 + macOS 10.12.6.
A workaround that did the trick for me was to build the fbsimctl from source in Xcode and find the binary in derived data folder. Copy it to a location in the `PATH` along without all its .framework files.

**Comment by pgodbole01** [comment]
Hi,
Can you please elaborate as I am unable to find binary in derived data folder.

**Comment by vincentkjj** [comment]
You could find it in the report navigator (last icon in Xcode's left pane), in the build log, it would show that the binary is linked in something like this image. The path after "Link" is what you are looking for.
Open that folder and copy all frameworks as well as the fbsimctl binary itself, you should be good to go.

<img width="772" alt="screen shot 2017-10-12 at 11 32 23 am" src="https://user-images.githubusercontent.com/1451117/31512883-506d046e-af41-11e7-9d0a-d7da2e36a9d4.png">

**Comment by pgodbole01** [comment]
Thanks @vincentkjj, it works!!!
