### ISSUE TITLE
Unable to read GCDWebServers.framework

### ISSUE THREAD

**Issue by pgodbole01** [facebook/FBSimulatorControl#457]
Hi,
While building fbsimctl with custom installation method, I am getting following error - 

Failed to read file or folder at /Users/pgodbole/Desktop/FBSimulatorControl-master/fbsimctl/Carthage/Checkouts/GCDWebServer/Carthage/Build/Mac/GCDWebServers.framework.

Please help me with this bug as it is causing trouble.

**Comment by pgodbole01** [comment]
Marking this issue as close as it won't occur any more.

**Comment by MoOx** [comment]
I am still facing this issue when trying to build from fbsimctl.xcworkspace , what did you do to fix this problem?

**Comment by pgodbole01** [comment]
Hi @MoOx, I canceled this bug because I removed dependency of fbsimctl on my project as it has no connection with XCUItest and I am not running on multiple simulators. If you still facing this, you must reopen this bug.
