### ISSUE TITLE
Build error: CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

### ISSUE THREAD

**Issue by MoOx** [facebook/FBSimulatorControl#471]
When running `brew install facebook/fb/fbsimctl --HEAD` currently it's impossible to get `fbsimctl`.

```
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64 /tmp/fbsimctl-20180221-62137-16aic6o/fbsimctl/FBSimulatorControlKit/Sources/SimulatorReporter.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/facebook/homebrew-fb/issues
```

Note: The last time I used this command (with SHA 1d7da93) it was working, but a coworker have to install this tool and brew offer no ways to install it via a commit SHA (and [don't want to](https://github.com/Homebrew/brew/issues/1738)).

Problem is latest "stable" (0.4.0) is very old and does not work with Xcode 9 (#435). So we are kind of stuck.

---

I know you are pretty busy at FB (poke @lawrencelomax) but it would be nice to get a new "release" so we can safely install a stable version at anytime this days :)
How can we help doing this?

**Comment by VincentCATILLON** [comment]
Is it really closed @MoOx ?

**Comment by zwebie** [comment]
I'm getting the same error.

**Comment by reach2jeyan** [comment]
@VincentCATILLON @MoOx I am getting the same error. Is there any update or a work around? I am using xcode9.3 CLI version to build

**Comment by MoOx** [comment]
I still use Xcode 9.2 and was recently able to build fbsimctl with it. Didn't try with 9.3

**Comment by reach2jeyan** [comment]
What did you do @MoOx Like, how did you avoid this error?

**Comment by MoOx** [comment]
Can't remember. Currently my team have a versionned version of this tool to avoid facing this kind of problem as this repo looks unstable (and not new stable tags are released).

You may want to take a look at this to see a more accurate error that might help you get rid of it https://stackoverflow.com/a/31265819/988941

**Comment by jbcrestot** [comment]
I am in the team where @MoOx  and @VincentCATILLON was at the time, and we just removed the "versionned" version of the tool from our repository.
It's working as intended now

**Comment by kuldipjagtap** [comment]
Hi,

I am also getting the same issue.

**Comment by ankit0409** [comment]
I am also getting the same issue. I was spent my whole day

**Comment by ankit0409** [comment]
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal x86_64 /Users/Data/myproject/AppSharedData/AppSharedData.swift
	CompileSwift normal x86_64 /Users/Data/myproject/CommonUtils.swift
	CompileSwift normal x86_64 /Users/Data/myproject/DrivehistoryTblCellTableViewCell.swift

**Comment by c-ryan747** [comment]
Hi fbsimctl is now longer being maintained, we strongly recommend moving to idb. Saying that if you want to fix the fbsimctl build we're happy to continue reviewing fbsimctl PRs for now.

**Comment by ruchiupgade-mb** [comment]
> ** BUILD FAILED **
> The following build commands failed:
> CompileSwift normal x86_64 /Users/Data/myproject/AppSharedData/AppSharedData.swift
> CompileSwift normal x86_64 /Users/Data/myproject/CommonUtils.swift
> CompileSwift normal x86_64 /Users/Data/myproject/DrivehistoryTblCellTableViewCell.swift

Getting these same issues in ADO Pipelines CI. Project is building successfully in local. But failing in CI.
