### ISSUE TITLE
launch_xctest fails on Xcode 10 beta 5

### ISSUE THREAD

**Issue by NickAb** [facebook/FBSimulatorControl#488]
Running `fbsimctl $UDID launch_xctest $ROOT/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.Preferences` fails on Xcode 10 beta 5.

**Steps**
```sh
# assuming you have WebDriverAgent built and located at $ROOT/
fbsimctl $UDID boot
fbsimctl $UDID launch_xctest $ROOT/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.Preferences
```

**Expected**

WebDriverAgent is started and listens on 8100

**Actual**

The operation fails with one of two errors depending on fbsimctl version

- HEAD-ec54965 - fbsimctl starts xctests and host application crashes immediately. Launching same host application using `fbsimctl launch` works fine, i.e. crash is related to xctest part.
    ```
    Error Domain=com.facebook.FBControlCore Code=0 "Timed out after 20.000000 seconds waiting for Connection to happen, _XCT_testBundleReadyWithProtocolVersion:minimumVersion: has not been called yet" UserInfo={NSLocalizedDescription=Timed out after 20.000000 seconds waiting for Connection to happen, _XCT_testBundleReadyWithProtocolVersion:minimumVersion: has not been called yet}
    ```
- HEAD-292a1bd - fbsimctl fails to start xctest
    ```
    2018-08-01 14:02:27.763 fbsimctl[27363:11072000] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[XCTestConfiguration setPathToXcodeReportingSocket:]: unrecognized selector sent to instance 0x7f80eac4d490'
    ```

**Environment**

```
$ system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: macOS 10.13.5 (17F77)

$ xcodebuild -version
Xcode 10.0
Build version 10L221o
```

Two different versions of fbsimctl were tried:

- `/usr/local/bin/fbsimctl -> ../Cellar/fbsimctl/HEAD-ec54965/bin/fbsimctl` - latest head at the moment
- `/usr/local/bin/fbsimctl -> ../Cellar/fbsimctl/HEAD-292a1bd/bin/fbsimctl` - previously extensivly  used version

Both iOS 11 and iOS 12 simulators were tried:
```
iPhone 6 | iOS 11.0 | x86_64
iPhone 6 | iOS 12.0 | x86_64
iPhone 8 | iOS 12.0 | x86_64
```

Crash logs of host applications and fbsimctl verbose outputs are attached.

[Contact.crash.txt](https://github.com/facebook/FBSimulatorControl/files/2249829/Contact.crash.txt)
[Preferences.crash.txt](https://github.com/facebook/FBSimulatorControl/files/2249830/Preferences.crash.txt)
[fbsimctl-ec54965.txt](https://github.com/facebook/FBSimulatorControl/files/2249832/fbsimctl-ec54965.txt)
[fbsimctl-HEAD-292a1bd.txt](https://github.com/facebook/FBSimulatorControl/files/2249833/fbsimctl-HEAD-292a1bd.txt)

**Comment by NickAb** [comment]
Can be related https://github.com/facebook/WebDriverAgent/issues/970#issuecomment-409775650

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
