### ISSUE TITLE
Make a Sample project that pulls in WebDriverAgent as a dependency

### ISSUE THREAD

**Issue by lawrencelomax** [facebook/FBSimulatorControl#5]
[```WebDriverAgent```](https://github.com/facebook/WebDriverAgent) is a strong use case for ```FBSimulatorControl```, we should have a convenient way of constructing the ```FBAgentLaunchConfiguration``` for it, rather than assuming it exists in the Frameworks's bundle.

**Comment by jaredly** [comment]
++1 I'd love to see this example

**Comment by lawrencelomax** [comment]
This is now documented in the [`WebDriverAgent` Wiki](https://github.com/facebook/WebDriverAgent/wiki/Starting-WebDriverAgent#c-using-fbsimctl-from-fbsimulatorcontrol-framework). With instructions about how to get this running with `fbsimctl`.
