### ISSUE TITLE
Example project needed

### ISSUE THREAD

**Issue by acunniffe** [facebook/FBSimulatorControl#50]
I may be stupid (although i'd wager I'm not) and no matter what I do I can't get this to link properly unless I embed the framework and I can't do that without a code signing issue. 

Love the potential and want to use this. Better install instructions or a pod spec would be alright too. 

Thanks.

**Comment by lawrencelomax** [comment]
I agree that a Podpsec would be a good idea, I just have to figure out the best way of providing linker flags to dependents of the Framework. 

>  can't get this to link properly unless I embed the framework and I can't do that without a code signing issue.

This suggests that you are using the Framework on an iOS binary. `FBSimulatorControl` links against OS X Frameworks. How is your project currently setup?

**Comment by acunniffe** [comment]
Good point - last I checked you were not able to do that with a Podspec. 

I am using OS X. Just dragged a release build of the framework into the project and linked to the OS X framework directories as you suggested. The strange thing is that all the things I linked to worked fine, but the library that threw this: "dyld: Library not loaded: @rpath/" was FBSimulatorControl. 

Perhaps I included the framework improperly?

**Comment by makhov** [comment]
Try to create a simple example:
https://github.com/makhov/fbsimulatorcontrol-example-cli-app

**Comment by SerenadeX** [comment]
+1 to this.  I really want to see if we can use this to test our iOS projects in multiple simulators at once (each different device).  Any word on better documentation for how this would work in that situation?

**Comment by PavithraRavichandran** [comment]
It would be helpful if we could get better documentation to start this and run the test in multiple devices..

**Comment by tapthaker** [comment]
+1 facing the same problem. 

`dyld: Library not loaded: @rpath/FBSimulatorControl.framework/Versions/A/FBSimulatorControl
Reason: image not found`

**Comment by lawrencelomax** [comment]
Currently on vacation so can't take a long look at this, but I've added a PR for `fbsimctl` in #66. It uses a workspace that uses the framework. The issue you are seeing is that the `FBSimulatorControl.framework` isn't on your `@rpath`. The way that I solve this for `fbsimctl` is to bundle with the executable in a `Frameworks` directory that is in the same directory as the executable

The Copy phase takes the built framework and bundles it:
<img width="838" alt="screen shot 2015-11-11 at 12 14 58" src="https://cloud.githubusercontent.com/assets/217883/11097542/07bbb464-886e-11e5-939a-a31e046195d5.png">

The 'Runpath Search Paths' adds the Framework directory to the binary's `rpath`:
<img width="709" alt="screen shot 2015-11-11 at 12 14 47" src="https://cloud.githubusercontent.com/assets/217883/11097543/0941d840-886e-11e5-959c-e2d34884b639.png">

**Comment by vodkhang** [comment]
I still cannot figure out the right way. I think that when I put -rpath here, it becomes like the following
![screen shot 2015-12-18 at 6 15 58 pm](https://cloud.githubusercontent.com/assets/170183/11891487/304be45a-a5b3-11e5-9e3b-1e95fceaf84f.png)

**Comment by lawrencelomax** [comment]
@vodkhang When #109 lands it will be a much simpler install process. I'm testing now and will update the documentation accordingly

**Comment by vodkhang** [comment]
@lawrencelomax thanks very much for that :)

**Comment by bootstraponline** [comment]
The readme states:

>  Test targets can be made that don't depend on any Application targets, or that launch multiple Application targets. This enables running against pre-built and archived Application binaries, rather than a binary that is built by a Test Target.

Is there an example project that demonstrates an iOS UITests target that runs against a pre-built Application binary?

**Comment by davidlawson** [comment]
I've set up a GUI for FBSimulatorControl here: https://github.com/davidlawson/SimulatorController
Also serves as a simple example project.

**Comment by lawrencelomax** [comment]
I'm happy to add Examples to the Readme or wiki for any examples that come along. Closing this out for now, if people want to raise specific issues or recommendation for documentation, that would be great.
