### ISSUE TITLE
fbsimctl build fails using Xcode 10.1 (HEAD@baf4b082)

### ISSUE THREAD

**Issue by swcisel** [facebook/FBSimulatorControl#501]
After Homebrew failed to install the latest fbsimctl, I attempted to compile it manually from source using `./build.sh fbsimctl build`, but it fails with the following error: 

```
...
▸ Compiling FBSimulatorImage.m
▸ Compiling FBSimulatorHIDEvent.m

❌  /Users/sean/source/FBSimulatorControl/FBSimulatorControl/HID/FBSimulatorHIDEvent.m:566:10: implicit conversion turns floating-point number into integer: 'double' to 'NSUInteger' (aka 'unsigned long') [-Werror,-Wfloat-conversion]

  return self.duration;
  ~~~~~~ ^~~~~~~~~~~~~


▸ Compiling FBSimulatorHID.m
▸ Compiling FBSimulatorError.m
▸ Compiling FBSimulatorEraseStrategy.m
▸ Compiling FBSimulatorEraseConfiguration.m
▸ Compiling FBSimulatorDiagnostics.m
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/sean/source/FBSimulatorControl/build/Build/Intermediates.noindex/FBSimulatorControl.build/Debug/FBSimulatorControl.build/Objects-normal/x86_64/FBSimulatorHIDEvent.o /Users/sean/source/FBSimulatorControl/FBSimulatorControl/HID/FBSimulatorHIDEvent.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
▸ Compiling FBSimulatorDeletionStrategy.m
```
I'm using MacOS 10.14.1 and Xcode 10.1

Edit: Closing, as #500 fixes the issue.

**Comment by galkahana** [comment]
if, like me, you have an automated testing system that you want to continue to run and you don't have the porblem resolved by other means, you can temporarilry use my fork of the fb tap that points to my solved fork of fbsimstl. replace your existing brew install with:

brew install https://raw.githubusercontent.com/galkahana/homebrew-fb/master/fbsimctl.rb --HEAD

**Comment by Insofan** [comment]
@galkahana I have encounting this problem And try  brew install https://raw.githubusercontent.com/galkahana/homebrew-fb/master/fbsimctl.rb --HEAD. It still error

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
