### ISSUE TITLE
Unable to createSessionForSimulatorConfiguration.

### ISSUE THREAD

**Issue by tapthaker** [facebook/FBSimulatorControl#65]
While creating the the session getting error the following error:

Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed to allocate simulator" UserInfo=0x618000077b80 {NSLocalizedDescription=Failed to allocate simulator, NSUnderlyingError=0x618000052810 "Failed to create a simulator with the name iPhone 5s"}

**Comment by lawrencelomax** [comment]
Have you downloaded the relevant Simulator Runtimes?

<img width="862" alt="screen shot 2015-11-11 at 12 18 54" src="https://cloud.githubusercontent.com/assets/217883/11097634/64672acc-886e-11e5-96c3-d09e5a8643f7.png">

**Comment by gblotter** [comment]
@tapthaker Can you post more of the stack trace?  I had a similar problem, but the error you pasted in wasn't the whole story and it ended up that when I was overriding the deviceSetPath, my path was wrong.

**Comment by tapthaker** [comment]
Couldn't reproduce this issue. A reboot had fixed things for me. Closing it.

**Comment by anshu10165** [comment]
@gblotter : Would you be able to help me , I got the error while I ran your project for understanding purpose:
SessionDefaultsProtocol -> createSession(): Failed to createSession with the following error: Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed to allocate simulator" UserInfo={NSLocalizedDescription=Failed to allocate simulator, NSUnderlyingError=0x7fb879c43170 {Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed to create a simulator with the name iPhone 6 Plus" UserInfo={NSLocalizedDescription=Failed to create a simulator with the name iPhone 6 Plus, NSUnderlyingError=0x7fb879c00be0 {Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument"}}}} 
DriveSimulators.TestRunner doTestLaunchesSingleSimulator(): Unable to create session

Thanks for the help.
