### ISSUE TITLE
Build fbsimctl

### ISSUE THREAD

**Issue by lawrencelomax** [facebook/FBSimulatorControl#70]
`fbsimctl` is a WIP subproject in the repo, using the `FBSimulatorControl.framework` from a separate workspace. It is a Swift-based mac CLI that aims to expose a bunch of the features in a way that doesn't require directly require interfacing with the framework. In is intended to be extended in the future and to do many of the things that `simctl` doesn't.

- [x] Create Umbrella header for `FBSimulatorControl` so it can be used externally in Swift
- [x] Add a new Target and CLI app called `fbsimctl` that uses `FBSimulatorControl`
- [x] Parser Combinators for the CLI commands
- [x] Query: Text representation of a Predicate for fetching simulators
- [x] Format: A Text representation of Simulators by querying for properties
- [x] `list`: Lists all Simulators by a query and a format
- [x] `boot`: Boots Simulators by a query
- [x] `shutdown`: Shuts down Simulators by a query
- [x] `upload`: Uploads photos and videos to a bunch of queried Simulators.
- [x] `diagnose`: Shows diagnostic information in a variety of formats.
- [x] `launch`: Launches applications and agents
- [x] `install`: Installs applications
- [x] `interact`: An interactive mode for `fbsimctl`
- [x] `stdout`/`stderr` based interactive mode
- [x] TCP Socket-Server based interactive mode
- [x] Hangup & `SIGTERM` tearing down simulators
- [ ] `help`: prints out help for a subcommand
- [x] Update the `README`

**Comment by vania-pooh** [comment]
@lawrencelomax so far as I can see simulator startup (boot command) is not yet implemented. However I would like to create a javascript binding for fbsimctl so could you please specify an expected syntax of commands:
* ```$ fbsimctl list {booted|booting|created|shutdown|shutting-down|<udid>|<part of name>}``` - show information about simulators
* ```$ fbsimctl interact``` - launch interactive mode
The following commands are competely unclear for me:
* ```$ fbsimctl boot```
* ```$ fbsimctl shutdown```
* ```$ fbsimctl diagnose```
So how do you expect to boot and shutdown simulators?

**Comment by lawrencelomax** [comment]
@vania-pooh I really hope that I can get to work on this over the coming months and have a few ideas about how to make this work. Many of the recent pull-requests are in service of making `fbsimctl` work reliably over multiple process invocations.

> So how do you expect to boot and shutdown simulators?

I want to use a [query grammar](https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/Sources/Command.swift#L46) that will describe the kinds of simulators that should be booted. This will allow for individual Simulators to be targeted and for multiple Simulators to be targeted with an individual command. This can have the same range of options that all the other commands that target Simulators take. The grammar that you listed for the `fbsimctl list` is along the lines of what I was thinking.

I don't yet know if this is totally appropriate, but I believe that it maps nicely to `simctl` commands and should make the CLI as intuitive as possible.

Note that there are additional configuration options in `FBSimulatorControl` such as the use of Custom DeviceSets, which [will also be an (optional) part of the grammar](https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/Sources/Command.swift#L25).

**Comment by vania-pooh** [comment]
@lawrencelomax according to your code ```boot``` command is implemented but I can't find any way to use it. Could you provide an example command using this functionality?

**Comment by lawrencelomax** [comment]
`fbsimctl boot <simulator-udid>` should work

**Comment by tapthaker** [comment]
@lawrencelomax : Eagerly waiting for fbsimctl to finish. Wanted to know how can I contribute so that 2 contributors aren't working on the same feature.

**Comment by vania-pooh** [comment]
@tapthaker JFYI I'm not working on the code

**Comment by lawrencelomax** [comment]
I won't have much of a chance to work on this over the next few weeks but hope to do so after that. Most of the big outstanding stuff relates to:
1) Building for [Homebrew]: #120 
2) Implementing the rest of the interactions
3) Persisting information about simulator allocation across invocations of the `fbsimctl` command to ensure that multiple `fbsimctl` instances can't modify the same `SimDeviceSet` at the same time.

**Comment by lawrencelomax** [comment]
I'm closing this in favor of making smaller tasks/requests. `help` being a priority
